# Generated by Django 3.0.7 on 2020-10-10 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapiest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('incident_date', models.DateTimeField(auto_now_add=True)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('victim', models.CharField(max_length=255)),
                ('punishment', models.CharField(max_length=400)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('In jail', 'In jail'), ('Police custady', 'police custady'), ('escaping', 'escaping')], default=1, max_length=255)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
