# Generated by Django 3.0.7 on 2020-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapiest',
            name='incident_date',
            field=models.DateTimeField(),
        ),
    ]
